spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.18.127:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.18.127:8080

server:
  port: 9091

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  sentinel:
    enabled: true