spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.18.127:8848

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: "*"